services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: good_services
      POSTGRES_PASSWORD: Goodservices.2025!
    volumes:
      - "./Backend/volumes_postgres:/var/lib/postgresql/data"
      - "./Backend/database/database_init.sql:/docker-entrypoint-initdb.d/database_init.sql"
    ports:
      - '5444:5432'
    #   - '5432:5432'
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5
  
  backend:
    container_name: goodservice
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    #   - '7000:80'
    #depends_on:
    #  database:
    #    condition: service_healthy

  #web:
  #  build: 
  #    context: ./Front
  #    dockerfile: Dockerfile
  #  container_name: miapp-nginx
  #  ports:
  #    - "8080:80"

