FROM nginx:latest

# Copia la configuración personalizada de Nginx
COPY default.conf /etc/nginx/conf.d/default.conf

# Copia el archivo HTML básico
COPY index.html /usr/share/nginx/html/index.html